name: Solarman MQTT Bridge
version: "1.0.1"
slug: solarman
description: "Bridge between Solarman PV inverter and Home Assistant via MQTT."
arch:
  - amd64
  - armv7
  - aarch64
startup: application
boot: auto
init: false
panel_icon: mdi:solar-power
options:
  name: "Solarman"
  url: "api.solarmanpv.com"
  appid: ""
  secret: ""
  username: ""
  password: ""
  orgId: ""
  stationId: 0
  inverterId: ""
  loggerId: 0
  interval: 300
  debug: false
  mqtt_broker: "10.10.10.10"
  mqtt_port: 1883
  mqtt_topic: "solarmanpv"
  mqtt_username: ""
  mqtt_password: ""
schema:
  name: str
  url: str
  appid: str
  secret: str
  username: str
  password: password
  orgId: str
  stationId: int
  inverterId: str
  loggerId: int
  interval: int
  debug: bool
  mqtt_broker: str
  mqtt_port: int
  mqtt_topic: str
  mqtt_username: str
  mqtt_password: password
build:
  dockerfile: Dockerfile
